image: node:20-alpine

variables:
  auth_service_path: "server/auth_service"
  appointment_service_path: "server/appointment_service"
  clinic_service_path: "server/clinic_service"
  notification_service_path: "server/notification_service"
  mock_data_path: "server/mock_data"
  shared_module_path: "shared"

stages:
  - build
  - test

build-auth-service:
  stage: build
  tags: 
    - docker
  script:
    - cd $auth_service_path
    - npm ci
    - npm run build
  artifacts:
    paths:
      - $auth_service_path/dist
    expire_in: 1 hour

build-appointment-service:
  stage: build
  tags: 
    - docker
  script:
    - cd $appointment_service_path
    - npm ci
    - npm run build
  artifacts:
    paths:
      - $appointment_service_path/dist
    expire_in: 1 hour

build-clinic-service:
  stage: build
  tags: 
    - docker
  script:
    - cd $clinic_service_path
    - npm ci
    - npm run build
  artifacts:
    paths:
      - $clinic_service_path/dist
    expire_in: 1 hour

test-appointment-service:
  stage: test
  tags:
    - docker
  needs:
    - build-appointment-service
  services:
    - name: mongo:latest
      alias: mongo-appointment
    - name: emqx/emqx:latest
      alias: mqtt-broker
  variables:
    MQTT_URI: mqtt://mqtt-broker:1883
    NODE_ENV: development
    MONGODB_URI: mongodb://mongo-appointment/appointment_db
  before_script:
    - apk add --no-cache mongodb-tools
    - mongoimport --uri mongodb://mongo-appointment:27017/appointment_db --collection slots --file $mock_data_path/appointment_db/seed_appointment_data.json --jsonArray --upsert --upsertFields _id
    - cd $shared_module_path/mqtt && npm ci && cd ../../
  script:
    - cd $appointment_service_path
    - npm ci
    - npm run start > app.log 2>&1 &
    - npm run test:integration
  artifacts:
    paths:
      - $appointment_service_path/app.log
    expire_in: 1 hour
  dependencies:
    - build-appointment-service
