version: '3.8'

services:
    # Frontend Web Application
    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        container_name: frontend
        restart: unless-stopped
        ports:
            - '4000:3000'
        volumes:
            # Optimize volume mounts
            - ./frontend:/app/frontend:cached
            - frontend_node_modules:/app/frontend/node_modules
            # Exclude .next folder from mounting
            - /app/frontend/.next
        env_file:
            - ./frontend/.env
        environment:
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
        networks:
            - network-cluster
        depends_on:
            - clinic-service
            - appointment-service
            - auth-service
            - mqtt-broker-lb

    # Clinic Service
    clinic-service:
        build:
            context: .
            dockerfile: server/clinic_service/Dockerfile
        container_name: clinic-service
        restart: unless-stopped
        ports:
            - '3300:3300'
        volumes:
            # Mount source code but exclude node_modules
            - ./server/clinic_service:/app/server/clinic_service:cached
            - ./shared:/app/shared:cached
            - clinic_service_node_modules:/app/server/clinic_service/node_modules
            - shared_node_modules:/app/shared/node_modules
        env_file:
            - ./server/clinic_service/.env
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - mongo-clinic
            - mqtt-broker-lb
        networks:
            - network-cluster

    # Appointment Service
    appointment-service:
        build:
            context: .
            dockerfile: server/appointment_service/Dockerfile
        container_name: appointment-service
        restart: unless-stopped
        ports:
            - '5000:5000'
        volumes:
            # Mount source code but exclude node_modules
            - ./server/appointment_service:/app/server/appointment_service:cached
            - ./shared:/app/shared:cached
            - appointment_service_node_modules:/app/server/appointment_service/node_modules
            - shared_node_modules:/app/shared/node_modules
        env_file:
            - ./server/appointment_service/.env
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - mongo-appointment
            - mqtt-broker-lb
            - redis_appointment
        networks:
            - network-cluster

    # Auth Service
    auth-service:
        build:
            context: .
            dockerfile: server/auth_service/Dockerfile
        container_name: auth-service
        restart: unless-stopped
        ports:
            - '4400:4400'
        volumes:
            - ./server/auth_service:/app/server/auth_service:cached
            - ./shared:/app/shared:cached
            - auth_service_node_modules:/app/server/auth_service/node_modules
            - shared_node_modules:/app/shared/node_modules
        env_file:
            - ./server/auth_service/.env
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - mongo-auth
            - mqtt-broker-lb
        networks:
            - network-cluster

    # Notification Service
    notification-service:
        build:
            context: .
            dockerfile: server/notification_service/Dockerfile
        container_name: notification-service
        restart: unless-stopped
        ports:
            - '6500:6500'
        volumes:
            - ./server/notification_service:/app/server/notification_service
            - ./shared:/app/shared
            - /app/server/notification_service/node_modules
            - /app/shared/node_modules
        env_file:
            - ./server/notification_service/.env
        environment:
            - NODE_ENV=development
        depends_on:
            - mongo-notification
            - mqtt-broker-lb
        networks:
            - network-cluster

    mqtt-broker:
        image: eclipse-mosquitto:2.0
        container_name: mqtt-broker
        volumes:
            - ./infrastructure/mqtt-broker/config:/mosquitto/config
        ports:
            - '1883:1883'
            - '9001:9001'
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        networks:
            - network-cluster
        restart: always

    mqtt-broker2:
        image: eclipse-mosquitto:2.0
        container_name: mqtt-broker2
        volumes:
            - ./infrastructure/mqtt-broker/config:/mosquitto/config
        ports:
            - '2883:1883'
            - '9002:9001'
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        networks:
            - network-cluster
        restart: always

    mqtt-broker3:
        image: eclipse-mosquitto:2.0
        container_name: mqtt-broker3
        volumes:
            - ./infrastructure/mqtt-broker/config:/mosquitto/config
        ports:
            - '3883:1883'
            - '9003:9001'
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        networks:
            - network-cluster
        restart: always

    mqtt-broker-lb:
        image: haproxy:2.6
        container_name: mqtt-broker-lb
        volumes:
            - ./infrastructure/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        ports:
            - '1884:1883'
            - '9004:9001'
            - '5001:5001'
        networks:
            - network-cluster
        depends_on:
            - mqtt-broker
            - mqtt-broker2
            - mqtt-broker3
        restart: always

    mongo-clinic:
        image: mongo:latest
        container_name: mongo-clinic
        ports:
            - '27018:27017'
        volumes:
            - ./infrastructure/database/clinic_data:/data/db
            - ./server/mock_data/clinic_db:/docker-entrypoint-initdb.d
        networks:
            - network-cluster

    mongo-appointment:
        image: mongo:latest
        container_name: mongo-appointment
        ports:
            - '27019:27017'
        volumes:
            - ./infrastructure/database/appointment_data:/data/db
            - ./server/mock_data/appointment_db:/docker-entrypoint-initdb.d
        networks:
            - network-cluster

    mongo-auth:
        image: mongo:latest
        container_name: mongo-auth
        ports:
            - '27020:27017'
        volumes:
            - ./infrastructure/database/auth_data:/data/db
        networks:
            - network-cluster

    mongo-notification:
        image: mongo:latest
        container_name: mongo-notification
        ports:
            - '27021:27017'
        volumes:
            - ./infrastructure/database/notification_data:/data/db
        networks:
            - network-cluster

    redis_appointment:
        image: redis:latest
        container_name: redis_appointment
        ports:
            - '27022:6379'
        volumes:
            - ./infrastructure/caching/appointment_data:/data
        networks:
            - network-cluster

volumes:
    frontend_node_modules:
    clinic_service_node_modules:
    appointment_service_node_modules:
    auth_service_node_modules:
    shared_node_modules:

networks:
    network-cluster:
        driver: bridge
